In [2]:
import numpy as np

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [5]:
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])
print(A[1, 2: 4])

[8 9]


In [7]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

B = A[:, 2]
B

array([ 3,  7, 11, 15])

In [3]:
A = np.array([[1, 1, 2, 3], 
              [4, 5, 1, 4], 
              [1, 9, 10, 11]])

print(A.sum(axis = 0))

[ 6 15 13 18]


In [4]:
A = np.array(([1, 2, 3]))
B = np.array([[4, 5, 6]])
print(A + B)

[[5 7 9]]


In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x @ y)

32


In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x * y)

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.dot(x, y))


x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.sum(x * y))

[ 4 10 18]
32
32


In [9]:
w = np.zeros(5)
w = w + 2
print(w)

[2. 2. 2. 2. 2.]


In [10]:
np.linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])